### ISSUE TITLE
失败信息，账号存在异常是什么？

### ISSUE THREAD

**Issue by XingY003** [fengx1a0/Bilibili_show_ticket_auto_order#101]
我试了一下 抢普通票可以，抢未开售的就显示这个
![屏幕截图 2024-04-08 204651](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/166401361/8c7952d3-6e01-4ead-bc4d-4f374bacf247)

**Comment by Just-Prog** [comment]
未开售票提前去获取token都是这个提示
