### ISSUE TITLE
刚抢票IP就被风控了，是因为购票只能APP上吗

### ISSUE THREAD

**Issue by Zackyooo** [fengx1a0/Bilibili_show_ticket_auto_order#103]
![111](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/26738991/dc52c482-3059-4885-bd4d-3ed91e47cddf)

而且我看这个提示也不是SSL什么的

**Comment by duobuhui** [comment]
开售瞬间我也是被风控，后续回流票就能正常挂了，不过现在一直是token已过期，不知道什么情况
