### ISSUE TITLE
滑块验证

### ISSUE THREAD

**Issue by yeahskr** [fengx1a0/Bilibili_show_ticket_auto_order#11]
DevTools listening on ws://
请在脚本目录打开此程序
请按任意键继续

**Comment by yeahskr** [comment]
DevTools listening on ws://
登录了，然后命令符没有任何提示

**Comment by fengx1a0** [comment]
> DevTools listening on ws://
> 登录了，然后命令符没有任何提示

滑块验证为监听模块，出现验证事件后触发

**Comment by fengx1a0** [comment]
解释说明issue

**Comment by yeahskr** [comment]
挂着就行了是吧？

**Comment by fengx1a0** [comment]
> 挂着就行了是吧？

对的，你这个情况不是特例，继续跑就行，真有问题我会修

**Comment by yeahskr** [comment]
ok，辛苦了！
