### ISSUE TITLE
为什么好几次bw显示成功但是订单页面没有？

### ISSUE THREAD

**Issue by mqc2426427558** [fengx1a0/Bilibili_show_ticket_auto_order#13]
呜呜哭死，用大佬脚本抢了21号，但是22号好几次都显示成功抢到，但是订单页面就没有待支付

**Comment by mqc2426427558** [comment]
还有快放个赞助码，我要给大佬打赏，真的好用

**Comment by zuoweimen68** [comment]
同问，显示了好几次抢到了，订单里没有。还有那个滑块验证是怎么弄，一直打开还是怎么样

**Comment by fengx1a0** [comment]
> 同问，显示了好几次抢到了，订单里没有。还有那个滑块验证是怎么弄，一直打开还是怎么样

历史issue回复里面有具体说明，这个不是我代码的问题，此问题关闭
