### ISSUE TITLE
关于无法登录的问题

### ISSUE THREAD

**Issue by zhuzichen-bilibili** [fengx1a0/Bilibili_show_ticket_auto_order#14]
![登录问题](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/69454478/1bd94afa-9722-4bc4-9df0-72611dafc296)

**Comment by fengx1a0** [comment]
> ![登录问题](https://user-images.githubusercontent.com/69454478/252674988-1bd94afa-9722-4bc4-9df0-72611dafc296.png)

我不知道uid超了15位不好意思，我自己uid6位，bilibili现在uid最高到多少了

**Comment by fengx1a0** [comment]
已修复
