### ISSUE TITLE
下了最新版的抢未开售的还是显示账号存在异常暂时无法购票？

### ISSUE THREAD

**Issue by Yueshen0403** [fengx1a0/Bilibili_show_ticket_auto_order#15]
![BBC73AE9-B121-49D5-8DEA-F43C59211B1E](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/138998373/05b14bec-482b-4e42-a368-6fe7481f0e2b)

**Comment by Yueshen0403** [comment]
> > 我试的是CJ的
> 
> 未开售你还想抢到吗，未开售我脚本能抢到你觉得我还会开源免费给你用吗

那没事了🤣那现在这个滑块验证不是打开之后验证一下，改成出现需要验证的事件的时候自己弹出来了？

**Comment by fengx1a0** [comment]
> > > 我试的是CJ的
> > 
> > 
> > 未开售你还想抢到吗，未开售我脚本能抢到你觉得我还会开源免费给你用吗
> 
> 那没事了🤣那现在这个滑块验证不是打开之后验证一下，改成出现需要验证的事件的时候自己弹出来了？

就是出现需要验证的事件的时候自己弹出来

**Comment by fengx1a0** [comment]
已解决

**Comment by bilibili-William-Who** [comment]
> 已解决

意思就是说这句提示词表达的是这个票还没开售对吗 我以为我的账号被封了
