### ISSUE TITLE
关于请求超时

### ISSUE THREAD

**Issue by MacYor** [fengx1a0/Bilibili_show_ticket_auto_order#16]
试了很多次都是这样 如何解决
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/109885877/56081755-6e52-4016-af41-2347bdb4d0c3)

**Comment by fengx1a0** [comment]
> 试了很多次都是这样 如何解决 ![image](https://user-images.githubusercontent.com/109885877/252717590-56081755-6e52-4016-af41-2347bdb4d0c3.jpeg)

以前close的issue提过，你请求过于频繁被叔叔封禁了，等5-30分钟就解封了，config.txt把sleep时间调高一点，安全值是1.7（只跑一个），其他卡死原因就是你网络的问题，程序本身除了网络没有其他资源型操作
