### ISSUE TITLE
关于显示已成功抢到票，但是订单界面没有的问题

### ISSUE THREAD

**Issue by zjk200245** [fengx1a0/Bilibili_show_ticket_auto_order#21]
![Cache_-2ee26892121b100f](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139327498/c86884c1-6380-4489-9072-c30f90ccb49f)
![Cache_-6154e5f1036ed6ea](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139327498/c1aae78d-5311-47d7-9393-0bc0ef812c10)

在使用这个脚本之后，已经连续几次出现了脚本显示“已成功抢到票”，但是第一时间去待付款界面查看却没有任何订单的情况，至今还没有成功的抢到票。我看另一个提问者也提出过相同的问题，请问是脚本出现bug了嘛？

**Comment by Andy-Chuck** [comment]
睿站抽风，详见 #2

**Comment by fengx1a0** [comment]
> ![Cache_-2ee26892121b100f](https://user-images.githubusercontent.com/139327498/252897696-c86884c1-6380-4489-9072-c30f90ccb49f.png) ![Cache_-6154e5f1036ed6ea](https://user-images.githubusercontent.com/139327498/252897703-c1aae78d-5311-47d7-9393-0bc0ef812c10.jpg)
> 
> 在使用这个脚本之后，已经连续几次出现了脚本显示“已成功抢到票”，但是第一时间去待付款界面查看却没有任何订单的情况，至今还没有成功的抢到票。我看另一个提问者也提出过相同的问题，请问是脚本出现bug了嘛？

已修复，增加检测，请看新版本
