### ISSUE TITLE
错误退出原因看这里

### ISSUE THREAD

**Issue by fengx1a0** [fengx1a0/Bilibili_show_ticket_auto_order#24]
错误号:412
由于触发哔哩哔哩安全风控策略，该次访问请求被拒绝。
The request was rejected because of the bilibili security control policy.
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/0dc589a8-2760-497e-bd1a-801dd70fae67)

**Comment by fengx1a0** [comment]
有其他闪退原因都可以补充

**Comment by wosinibaba999** [comment]
怎么解决
