### ISSUE TITLE
我想请教一下那个验证脚本的作用

### ISSUE THREAD

**Issue by zjutcaicai** [fengx1a0/Bilibili_show_ticket_auto_order#25]
他是可以帮你自动滑滑块吗？

**Comment by fengx1a0** [comment]
> 他是可以帮你自动滑滑块吗？

需要验证的时候浏览器自动加载到滑块页面让你滑，手动

**Comment by zjutcaicai** [comment]
我在抢的时候发现了，就是会有报错信息让我重新验证。自动滑块的方法是不是没办法搞得，这样的话抢票我就需要每隔几分钟要重新滑块一次，没办法连夜挂着抢。
