### ISSUE TITLE
间隔1.7还是闪退了

### ISSUE THREAD

**Issue by superset245** [fengx1a0/Bilibili_show_ticket_auto_order#26]
RT，向作者反馈一下这个情况，1.7挂了半个小时左右闪退了

**Comment by fengx1a0** [comment]
> RT，向作者反馈一下这个情况，1.7挂了半个小时左右闪退了

1是速率，2是区间内总数，当然也跟网有关系，b站全国有cdn，我的建议是提高速度然后ban了换网或者休息一段时间，这样命中率比较高，今天开始普遍的ban的多了，可能和那边开始动手了
