### ISSUE TITLE
代码里判断“实名认证”建议再判断个“实名登记”，因为BML的api接口title里写的是“实名登记”

### ISSUE THREAD

**Issue by mikuxin** [fengx1a0/Bilibili_show_ticket_auto_order#27]

**Comment by mikuxin** [comment]
建议补上，刚刚用脚本抢票发现居然没有让我选购票人实名信息，就发现不对劲，明明BML是要实名的，结果这上面就不要，后来看API发现判断的字不对，孩子还想抢第二轮的票子，QAQ

**Comment by fengx1a0** [comment]
> 建议补上，刚刚用脚本抢票发现居然没有让我选购票人实名信息，就发现不对劲，明明BML是要实名的，结果这上面就不要，后来看API发现判断的字不对，孩子还想抢第二轮的票子，QAQ


你好，麻烦看清版本更新与修复，今天下午提交的版本已经修复了此问题，[0d2112184e572bce0a64eb2c47b5be385c71e1b0](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/commit/0d2112184e572bce0a64eb2c47b5be385c71e1b0)

**Comment by mikuxin** [comment]
嗯嗯好的，谢谢大佬~
