### ISSUE TITLE
412愈发频繁了

### ISSUE THREAD

**Issue by superset245** [fengx1a0/Bilibili_show_ticket_auto_order#28]
谢谢作者的持续更新，但是因为叔叔的出手，1.7安全间隔也不再安全了，有没有什么相对更加安全有效的设置方式，如果长期被BAN有解决办法吗

**Comment by fengx1a0** [comment]
> 谢谢作者的持续更新，但是因为叔叔的出手，1.7安全间隔也不再安全了，有没有什么相对更加安全有效的设置方式，如果长期被BAN有解决办法吗

他服务器封控你你能有啥办法，因为你确实在一直请求，我有以下几个解决办法：1.设置代理池，在config.txt中可以配置。2.设置代理，类似于梯子。3.自行换ip

**Comment by weijifen123** [comment]
请问这个bw和bml都可以抢吗

**Comment by fengx1a0** [comment]
> 请问这个bw和bml都可以抢吗

当然
