### ISSUE TITLE
geetest改进思路

### ISSUE THREAD

**Issue by BestLemoon** [fengx1a0/Bilibili_show_ticket_auto_order#29]
其实可以每隔一段时间检测url文件是否存在，且验证成功后可以删除url文件以防多次弹验证（实际并没有弹），直接使用pause感觉有点草率了，真正需要验证的时候也在pause。
```python
def mult_work(self):
    self.init_browser()
    self.load_cookies()
    while True:
        sleep(1)
        if not os.path.exists("url"):
            print("等待中")
            continue
        a = open("url", "r")
        u = a.read()
        a.close()
        if u and u.strip() != self.u:
            self.u = u
            # win32api.MessageBox(0,'需要滑块验证！','通知',win32con.MB_OK)
            self.WebDriver.get(u)
            os.remove("url")
            self.WebDriver.quit()
        # print("等待中")
```

**Comment by fengx1a0** [comment]
> 其实可以每隔一段时间检测url文件是否存在，且验证成功后可以删除url文件以防多次弹验证（实际并没有弹），直接使用pause感觉有点草率了，真正需要验证的时候也在pause。
> 
> ```python
> def mult_work(self):
>     self.init_browser()
>     self.load_cookies()
>     while True:
>         sleep(1)
>         if not os.path.exists("url"):
>             print("等待中")
>             continue
>         a = open("url", "r")
>         u = a.read()
>         a.close()
>         if u and u.strip() != self.u:
>             self.u = u
>             # win32api.MessageBox(0,'需要滑块验证！','通知',win32con.MB_OK)
>             self.WebDriver.get(u)
>             os.remove("url")
>             self.WebDriver.quit()
>         # print("等待中")
> ```

你测试过了吗

**Comment by BestLemoon** [comment]
> 
一直没出验证，正在测试中，同时需要修改`api.py`中判断errno的逻辑，当errno为100051时，也需重新获取token。

**Comment by fengx1a0** [comment]
> > > 其实可以每隔一段时间检测url文件是否存在，且验证成功后可以删除url文件以防多次弹验证（实际并没有弹），直接使用pause感觉有点草率了，真正需要验证的时候也在pause。
> > > ```python
> > > def mult_work(self):
> > >     self.init_browser()
> > >     self.load_cookies()
> > >     while True:
> > >         sleep(1)
> > >         if not os.path.exists("url"):
> > >             print("等待中")
> > >             continue
> > >         a = open("url", "r")
> > >         u = a.read()
> > >         a.close()
> > >         if u and u.strip() != self.u:
> > >             self.u = u
> > >             # win32api.MessageBox(0,'需要滑块验证！','通知',win32con.MB_OK)
> > >             self.WebDriver.get(u)
> > >             os.remove("url")
> > >             self.WebDriver.quit()
> > >         # print("等待中")
> > > ```
> > 
> > 
> > 你测试过了吗
> 
> 一直没出验证，正在测试中，同时需要修改`api.py`中判断errno的逻辑，当errno为100051时，也需重新获取token。

你没测试就贴上来嘛（），还有errno为100051的情况我昨天就修复了，不知道您用的哪个版本

**Comment by BestLemoon** [comment]
> > > > 其实可以每隔一段时间检测url文件是否存在，且验证成功后可以删除url文件以防多次弹验证（实际并没有弹），直接使用pause感觉有点草率了，真正需要验证的时候也在pause。
> > > > ```python
> > > > def mult_work(self):
> > > >     self.init_browser()
> > > >     self.load_cookies()
> > > >     while True:
> > > >         sleep(1)
> > > >         if not os.path.exists("url"):
> > > >             print("等待中")
> > > >             continue
> > > >         a = open("url", "r")
> > > >         u = a.read()
> > > >         a.close()
> > > >         if u and u.strip() != self.u:
> > > >             self.u = u
> > > >             # win32api.MessageBox(0,'需要滑块验证！','通知',win32con.MB_OK)
> > > >             self.WebDriver.get(u)
> > > >             os.remove("url")
> > > >             self.WebDriver.quit()
> > > >         # print("等待中")
> > > > ```
> > > 
> > > 
> > > 你测试过了吗
> > 
> > 
> > 一直没出验证，正在测试中，同时需要修改`api.py`中判断errno的逻辑，当errno为100051时，也需重新获取token。
> 
> 你没测试就贴上来嘛（），还有errno为100051的情况我昨天就修复了，不知道您用的哪个版本

看到了喵（确实用的是前天的版本
