### ISSUE TITLE
大佬抢了一上午显示账号存在异常无法购票了

### ISSUE THREAD

**Issue by sycice** [fengx1a0/Bilibili_show_ticket_auto_order#30]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/49969740/266eec5b-be82-457b-9026-ae957c5b140c)

**Comment by Andy-Chuck** [comment]
停售锁票了，14号中午12点放票

**Comment by sycice** [comment]
好的明白了

**Comment by Andy-Chuck** [comment]
这个Issue留着别关吧，让更多的人能看到，别提重复问题了

**Comment by Pancat009** [comment]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/134357830/732d09a7-cf7c-4f28-be17-dc83e19cea9d)
这个也是同样的问题？所以意思是已经开抢，等着就好了？

**Comment by Pancat009** [comment]
> ![image](https://user-images.githubusercontent.com/134357830/253465914-732d09a7-cf7c-4f28-be17-dc83e19cea9d.png) 这个也是同样的问题？所以意思是已经开抢，等着就好了？

失败了，抢不到。。

**Comment by fengx1a0** [comment]
> > ![image](https://user-images.githubusercontent.com/134357830/253465914-732d09a7-cf7c-4f28-be17-dc83e19cea9d.png) 这个也是同样的问题？所以意思是已经开抢，等着就好了？
> 
> 失败了，抢不到。。

这不是我的项目谢谢，去你下载的项目人那提issue谢谢

**Comment by fengx1a0** [comment]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/d8a78afc-886e-4d8a-9105-b9b1538ed37e)
声明一下我的项目长这样
