### ISSUE TITLE
新版本不触发风控，意思是理论上抢票间隔可以很短吗

### ISSUE THREAD

**Issue by weijifen123** [fengx1a0/Bilibili_show_ticket_auto_order#31]

**Comment by weijifen123** [comment]
比如设置半秒一次

**Comment by fengx1a0** [comment]
> 比如设置半秒一次

我可没说过不会触发封控，我只说过修复封控时直接闪退的问题，现在不闪退了，要是能不触发风控b站应该找我去上班

**Comment by weijifen123** [comment]
> > 比如设置半秒一次
> 
> 我可没说过不会触发封控，我只说过修复封控时直接闪退的问题，现在不闪退了，要是能不触发风控b站应该找我去上班

不好意思理解错了……请问一般间隔多少秒不容易触发风控啊

**Comment by fengx1a0** [comment]
> > > 比如设置半秒一次
> > 
> > 
> > 我可没说过不会触发封控，我只说过修复封控时直接闪退的问题，现在不闪退了，要是能不触发风控b站应该找我去上班
> 
> 不好意思理解错了……请问一般间隔多少秒不容易触发风控啊


目前是1.7秒以上
