### ISSUE TITLE
账号存在异常与弹出token但好像没跳出支付界面

### ISSUE THREAD

**Issue by sans233333** [fengx1a0/Bilibili_show_ticket_auto_order#32]
测试bw那边的票的时候就弹出账号异常是不是应该关了梯子,不过其他的展会是可以正确抢票可是提示了成功后没有支付界面。

**Comment by suhang56** [comment]
抢票成功之后回到手机会员购 点开未支付订单就好了。 BW没开票无法继续滑块认证所以异常。

**Comment by homulakk** [comment]
> 测试bw那边的票的时候就弹出账号异常是不是应该关了梯子,不过其他的展会是可以正确抢票可是提示了成功后没有支付界面。

1.bw账号异常是因为暂时停售了，明天中午会重新开始
2.请自行到手机app-会员购-右上角我的-待付款里支付
