### ISSUE TITLE
假票检测出现检测失误

### ISSUE THREAD

**Issue by Just-Prog** [fengx1a0/Bilibili_show_ticket_auto_order#33]
假票检测功能目前是检测订单第一条的 `status` 字段是否为 `1` ，是则鉴定为真票，

但如果使用者的第一条订单信息为会员购中未补尾款的手办等商品，其 `status` 字段也为 `1`，而票没有真正抢到时，程序会误报为真票从而自动停止

目前没试出来其他会触发这个BUG的订单信息

**Comment by Just-Prog** [comment]
目前我和我朋友两个号都出现过这个问题，现在BW暂时停售没法复现假票

**Comment by fengx1a0** [comment]
> 假票检测功能目前是检测订单第一条的 `status` 字段是否为 `1` ，是则鉴定为真票，
> 
> 但如果使用者的第一条订单信息为会员购中未补尾款的手办等商品，其 `status` 字段也为 `1`，而票没有真正抢到时，程序会误报为真票从而自动停止
> 
> 目前没试出来其他会触发这个BUG的订单信息

首先请尊重我的开源项目，谢谢。其次，你所提问题应该是有真实复现过的，虽然bw停售但是你可以用其他在售漫展演出票来测。最后，我的请求的是bilibili票务订单列表而不是会员购列表所以不会出现你所说的问题，谢谢。

**Comment by Just-Prog** [comment]
> > 假票检测功能目前是检测订单第一条的 `status` 字段是否为 `1` ，是则鉴定为真票，
> > 但如果使用者的第一条订单信息为会员购中未补尾款的手办等商品，其 `status` 字段也为 `1`，而票没有真正抢到时，程序会误报为真票从而自动停止
> > 目前没试出来其他会触发这个BUG的订单信息
> 
> 首先请尊重我的开源项目，谢谢。其次，你所提问题应该是有真实复现过的，虽然bw停售但是你可以用其他在售漫展演出票来测。最后，我的请求的是bilibili票务订单列表而不是会员购列表所以不会出现你所说的问题，谢谢。

没有冒犯和不尊重您的项目的意思，如果让您产生了冒犯的感觉我很抱歉，sorry。

其次，我本地复现的时候使用的是与您相同的票务中心的接口（即 `https://show.bilibili.com/api/ticket/ordercenter/list`），也的的确确意外返回了会员购的商品详情。

![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/62735122/4efb9656-0040-43fd-9b00-93ade67e2fe9)

抱歉让您感到被冒犯，祝您生活愉快。

**Comment by fengx1a0** [comment]
> > > 假票检测功能目前是检测订单第一条的 `status` 字段是否为 `1` ，是则鉴定为真票，
> > > 但如果使用者的第一条订单信息为会员购中未补尾款的手办等商品，其 `status` 字段也为 `1`，而票没有真正抢到时，程序会误报为真票从而自动停止
> > > 目前没试出来其他会触发这个BUG的订单信息
> > 
> > 
> > 首先请尊重我的开源项目，谢谢。其次，你所提问题应该是有真实复现过的，虽然bw停售但是你可以用其他在售漫展演出票来测。最后，我的请求的是bilibili票务订单列表而不是会员购列表所以不会出现你所说的问题，谢谢。
> 
> 没有冒犯和不尊重您的项目的意思，如果让您产生了冒犯的感觉我很抱歉，sorry。
> 
> 其次，我本地复现的时候使用的是与您相同的票务中心的接口（即 `https://show.bilibili.com/api/ticket/ordercenter/list`），也的的确确意外返回了会员购的商品详情。
> 
> ![image](https://user-images.githubusercontent.com/62735122/253413872-4efb9656-0040-43fd-9b00-93ade67e2fe9.png)
> 
> 抱歉让您感到被冒犯，祝您生活愉快。

你好，我当时测试的api和我所写api不一致，当时抄的群里建议的api，没有注意有几个单词不一样哈哈哈哈哈，代码层面看确实是我的问题，在新版本已修复，https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/releases/tag/v1.6.1。

**Comment by fengx1a0** [comment]
![X~{9IJ0_{V28PCT8(POJB0L](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/80448291-d6eb-4fc1-8a9f-2041480dba62)

今天才看到这个order和OrderCenter挺意外的，我为我的鲁莽自罚一杯

**Comment by Piwry** [comment]
> > > > 假票检测功能目前是检测订单第一条的 `status` 字段是否为 `1` ，是则鉴定为真票，
> > > > 但如果使用者的第一条订单信息为会员购中未补尾款的手办等商品，其 `status` 字段也为 `1`，而票没有真正抢到时，程序会误报为真票从而自动停止
> > > > 目前没试出来其他会触发这个BUG的订单信息
> > > 
> > > 
> > > 首先请尊重我的开源项目，谢谢。其次，你所提问题应该是有真实复现过的，虽然bw停售但是你可以用其他在售漫展演出票来测。最后，我的请求的是bilibili票务订单列表而不是会员购列表所以不会出现你所说的问题，谢谢。
> > 
> > 
> > 没有冒犯和不尊重您的项目的意思，如果让您产生了冒犯的感觉我很抱歉，sorry。
> > 其次，我本地复现的时候使用的是与您相同的票务中心的接口（即 `https://show.bilibili.com/api/ticket/ordercenter/list`），也的的确确意外返回了会员购的商品详情。
> > ![image](https://user-images.githubusercontent.com/62735122/253413872-4efb9656-0040-43fd-9b00-93ade67e2fe9.png)
> > 抱歉让您感到被冒犯，祝您生活愉快。
> 
> 你好，我当时测试的api和我所写api不一致，当时抄的群里建议的api，没有注意有几个单词不一样哈哈哈哈哈，代码层面看确实是我的问题，在新版本已修复，https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/releases/tag/v1.6.1

路过吐槽一句

早上看见了这个 issue，读完并测试后为 issue 发起者打抱不平于是洋洋洒洒叠甲+取证写了快 1k 字准备发个新 issue

没想到刚写完发现您这边更新了（

（单纯只是吐槽；本身我那个 issue 多少也带点个人恩怨）

最后加一句个人的碎碎念：我平常遇到自己的代码被指出错误（以前高中竞赛，在 luogu 上发的题解等），都会自己仔细查阅代码、调试，确认究竟是否存在问题再进行回复，看您这次的情况应该是没那么做（或者不太够细心qaq）

加上您一开始回复的措辞就比较激烈（至少我个人感受吧，比如 ”首先请尊重我的开源项目“），所以我一时就打抱不平特别上头（

**Comment by fengx1a0** [comment]
> 

我的问题，我测试了两遍没有发现我测试的api和我抄的代码不是一个api，实在没注意一个单词之差，是我的问题，我向所有看到这条issue的开发者道歉，对不起！

**Comment by Just-Prog** [comment]
> ![X~{9IJ0_{V28PCT8(POJB0L](https://user-images.githubusercontent.com/74698099/253444003-80448291-d6eb-4fc1-8a9f-2041480dba62.png)
> 
> 今天才看到这个order和OrderCenter挺意外的，我为我的鲁莽自罚一杯

这个API我两天前二次开发的时候也发现过，不过没太当回事，早上自己修Bug的时候也只是基于 `orderCenter` 版的原逻辑加了一条字符串验证。

您目前版本的验证方法很好，比我的Dirty Fix好

**Comment by fengx1a0** [comment]
> > ![X~{9IJ0_{V28PCT8(POJB0L](https://user-images.githubusercontent.com/74698099/253444003-80448291-d6eb-4fc1-8a9f-2041480dba62.png)
> > 今天才看到这个order和OrderCenter挺意外的，我为我的鲁莽自罚一杯
> 
> 这个API我两天前二次开发的时候也发现过，不过没太当回事，早上自己修Bug的时候也只是基于 `orderCenter` 版的原逻辑加了一条字符串验证。
> 
> 您目前版本的验证方法很好，比我的Dirty Fix好

这次是我自己抄的太草率没看清他fix的api具体路径，导致我以为和我测试的api一样，这条issue是我的问题，希望你能原谅我的鲁莽，这条issue我就先关闭了
