### ISSUE TITLE
网页登录后，程序没反应

### ISSUE THREAD

**Issue by Eas1o** [fengx1a0/Bilibili_show_ticket_auto_order#36]
edge登录后程序没反应

**Comment by Andy-Chuck** [comment]
请贴个图详细说明一下情况

**Comment by Eas1o** [comment]
![QQ截图20230714001415](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139485398/706d38a9-4774-40e3-9572-f7811a0d5de7)

**Comment by Eas1o** [comment]
网页登录了b站，程序开着没反应

**Comment by Andy-Chuck** [comment]
请在自动弹出的浏览器窗口登录睿站

**Comment by fengx1a0** [comment]
> 网页登录了b站，程序开着没反应

请用程序登录，第一次启动需要等3-5分钟看电脑配置
