### ISSUE TITLE
已经在闲鱼看见有人用这脚本抢票还直接挂详情里了啊嗯

### ISSUE THREAD

**Issue by Enana0430** [fengx1a0/Bilibili_show_ticket_auto_order#4]
![Screenshot_2023-07-10-11-56-33-89_0dff84d2da4d0ad](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139095930/03f6883b-738c-4aed-92c0-48fe33756f5d)

**Comment by fengx1a0** [comment]
已下架，感谢反馈，后面再有明目张胆的麻烦兄台再提
