### ISSUE TITLE
现在版本应该怎么使用？

### ISSUE THREAD

**Issue by wanog** [fengx1a0/Bilibili_show_ticket_auto_order#40]
没找到说明里的登录.exe等，大佬能否教一下怎么用？

**Comment by fengx1a0** [comment]
运行这个
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/74698099/d8590885-8b01-4c90-8e5d-a421cfafbd25)

**Comment by wanog** [comment]
![屏幕截图 2023-07-14 102100](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/93205631/05f9ef92-de84-4705-9df0-26561fd9dc75)
好像没看到。

**Comment by fengx1a0** [comment]
这 https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/releases/download/v1.6.1/ticket_auto_order_x64_v1.6.1.zip
