### ISSUE TITLE
请问如何抢多张票票

### ISSUE THREAD

**Issue by Lh1aS** [fengx1a0/Bilibili_show_ticket_auto_order#41]
一次抢票流程是登录，运行，滑块。那么可以多个运行窗口抢不同日期类型的票吗？还是说得登录，运行，滑块三步全部重新来。

**Comment by fengx1a0** [comment]
抢票可以多开，目前只能同一个账号

**Comment by zjutcaicai** [comment]
那我是不是可以一个执行exe，一个跑.py，这样可以实现两个账号抢吗

**Comment by fengx1a0** [comment]
> 那我可以创建两个项目，一个执行exe，一个跑.py，这样可以实现两个账号抢吗

两个都跑exe即可
