### ISSUE TITLE
多项目抢票问题

### ISSUE THREAD

**Issue by zjutcaicai** [fengx1a0/Bilibili_show_ticket_auto_order#43]
佬，我想请教一下，我有两个账号，然后我创建两个项目，分别存储账号信息，一个执行exe抢票，一个执行.py抢票，同时抢票可行吗？或者说我只需要执行各自的exe。

**Comment by fengx1a0** [comment]
> 佬，我想请教一下，我有两个账号，然后我创建两个项目，分别存储账号信息，一个执行exe抢票，一个执行.py抢票，同时抢票可行吗？或者说我只需要执行各自的exe。

分两个文件夹就行，每个文件夹都按流程跑

**Comment by fengx1a0** [comment]
可以都运行exe
