### ISSUE TITLE
程序闪退崩溃

### ISSUE THREAD

**Issue by Lh1aS** [fengx1a0/Bilibili_show_ticket_auto_order#46]
出现“抢票成功正在查询票务状态”后闪退，抢票中途也有闪退崩溃发生。后者偶尔，前者发生很多次。
补充：输入链接https://show.bilibili.com/platform/detail.htmlmsource=mall_piaowu_pc_14901_banner&id=73710&from=pwng-pc
后按回车确认大概率闪退。

**Comment by Just-Prog** [comment]
B站票务中心目前访问拥堵，闪退应该是因为B站返回了以下信息：

`{"errno":100001,"errtag":0,"msg":"请慢一点哟 ( ⊙ o ⊙ )！","data":{}}`

**Comment by Lh1aS** [comment]
![I273VI@6ON8_~_F_2X GERP](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139507138/f111f1de-e8a8-47a9-b071-416883a618ea)

**Comment by Lh1aS** [comment]
![~UP8ER@9 0}2T$L6UGYR5FG](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139507138/274997a6-a4c6-46c3-a767-dbe466bd701a)

**Comment by Just-Prog** [comment]
你好，郁先生，请您在提问时注意保护自己的个人隐私。

**Comment by Lh1aS** [comment]
> 你好，郁先生，请您在提问时注意保护自己的个人隐私。

抱歉，谢谢提醒

**Comment by Lh1aS** [comment]
更正，成功抢到一张。感谢作者

**Comment by Just-Prog** [comment]
> > 你好，郁先生，请您在提问时注意保护自己的个人隐私。
> 
> 抱歉，谢谢提醒

然而实际上从issue的修订记录还是能看见

请时刻留有隐私安全意识。

**Comment by Lh1aS** [comment]
> > > 你好，郁先生，请您在提问时注意保护自己的个人隐私。
> > 
> > 
> > 抱歉，谢谢提醒
> 
> 然而实际上从issue的修订记录还是能看见
> 
> 请时刻留有隐私安全意识。

多谢提醒，今后会注意的。

**Comment by GrayAndCyan** [comment]
`输入链接https://show.bilibili.com/platform/detail.htmlmsource=mall_piaowu_pc_14901_banner&id=73710&from=pwng-pc
后按回车确认大概率闪退。`
有可能是多打回车，复制的内容结尾带上了换行导致。

**Comment by Lh1aS** [comment]
追加：开抢一小时后已无闪退现象，但是“假票（同时锁定一张票，但是被其他人抢走了）”开始频繁出现

**Comment by fengx1a0** [comment]
> 追加：开抢一小时后已无闪退现象，但是“假票（同时锁定一张票，但是被其他人抢走了）”开始频繁出现

以上情况均为正常响应，只要正常运行都继续跑就行，第一个闪退是你会员购没订单或者是请求太快被风控了导致请求包没发出去自己看订单列表成功没就行
