### ISSUE TITLE
抢太快了被判定为脚本，让我慢一点

### ISSUE THREAD

**Issue by humpyalpha** [fengx1a0/Bilibili_show_ticket_auto_order#47]
![JPEG_20230714_125824_4178358802217482195](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139528308/500058ea-5bff-4c57-9da1-8a037c797e50)

**Comment by Lh1aS** [comment]
哈哈哈，我3个程序跑了45分钟，期间不断闪退重开闪退重开，我就怕睿站给我封了

**Comment by Enana0430** [comment]
他提示请慢点是正常的，你这个情况先把验证码划了然后放他在那挂就可以，真封IP会写IP可能被风控的

**Comment by GrayAndCyan** [comment]
这是滑块没滑导致把？

**Comment by Lh1aS** [comment]
> 这是滑块没滑导致把？

看上去像滑块没滑，有时候会有大量请求滑块

**Comment by fengx1a0** [comment]
滑块没拉哥们
