### ISSUE TITLE
总是出现网络问题

### ISSUE THREAD

**Issue by Lh1aS** [fengx1a0/Bilibili_show_ticket_auto_order#49]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139507138/60fcd549-9776-4168-8a17-24966d75d3a2)
如图，检查票务状态的时候会一直弹出网络问题，一直循环

**Comment by fengx1a0** [comment]
> ![image](https://user-images.githubusercontent.com/139507138/253522619-60fcd549-9776-4168-8a17-24966d75d3a2.png) 如图，检查票务状态的时候会一直弹出网络问题，一直循环

是新版本吗

**Comment by Lh1aS** [comment]
> > ![image](https://user-images.githubusercontent.com/139507138/253522619-60fcd549-9776-4168-8a17-24966d75d3a2.png) 如图，检查票务状态的时候会一直弹出网络问题，一直循环
> 
> 是新版本吗

没错，是之前发的新版本1.6.2那个

**Comment by Lh1aS** [comment]
> 

使用手机热点，切换wifi，使用网络代理均无法解决

**Comment by fengx1a0** [comment]
> > 
> 
> 使用手机热点，切换wifi，使用网络代理均无法解决

我的意思是你是不是用的最新版

**Comment by fengx1a0** [comment]
> > > ![image](https://user-images.githubusercontent.com/139507138/253522619-60fcd549-9776-4168-8a17-24966d75d3a2.png) 如图，检查票务状态的时候会一直弹出网络问题，一直循环
> > 
> > 
> > 是新版本吗
> 
> 没错，是之前发的新版本1.6.2那个

1.6.2我发了两个版本，第二个版本改掉了第一个版本的代码

**Comment by Lh1aS** [comment]
> > > > ![image](https://user-images.githubusercontent.com/139507138/253522619-60fcd549-9776-4168-8a17-24966d75d3a2.png) 如图，检查票务状态的时候会一直弹出网络问题，一直循环
> > > 
> > > 
> > > 是新版本吗
> > 
> > 
> > 没错，是之前发的新版本1.6.2那个
> 
> 1.6.2我发了两个版本，第二个版本改掉了第一个版本的代码

我使用的前一个1.6.2，现在尝试第二个版本

**Comment by fengx1a0** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/139507138/253522619-60fcd549-9776-4168-8a17-24966d75d3a2.png) 如图，检查票务状态的时候会一直弹出网络问题，一直循环
> > > > 
> > > > 
> > > > 是新版本吗
> > > 
> > > 
> > > 没错，是之前发的新版本1.6.2那个
> > 
> > 
> > 1.6.2我发了两个版本，第二个版本改掉了第一个版本的代码
> 
> 我使用的前一个1.6.2，现在尝试第二个版本

第二个版本彻底修复，有问题记得看看更新
