### ISSUE TITLE
大佬救！多开出bug自动退出后单开n次尝试后仍然宕机自动退出！

### ISSUE THREAD

**Issue by U7ii** [fengx1a0/Bilibili_show_ticket_auto_order#5]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/53084951/2af91737-0ad0-4229-b3a9-6ffb3fc82c8b)

开了两个抢票.exe同时运行然后闪退了，之后单开一个尝试抢双人普票后若干次尝试后仍然卡住闪退！想知道为什么不能一直运行下去，通常在第10次到140次之间的第n次就停止工作闪退了...**救救T~T**

**Comment by fengx1a0** [comment]
> ![image](https://user-images.githubusercontent.com/53084951/252248254-763cbf8b-cc43-4a76-83de-32d579b8777f.png)
> 
> 开了两个抢票.exe同时运行然后闪退了，之后单开一个尝试抢双人普票后若干次尝试后仍然卡住闪退！想知道为什么不能一直运行下去，通常在第10次到140次之间的第n次就停止工作闪退了...**救救T~T**

加qq群：818884376 ，你这个问题我还没遇到过，可以尝试改一下config.txt的sleep时间，也就是请求间隔
