### ISSUE TITLE
建议导入pyttsx3进行抢票成功后的语音提示

### ISSUE THREAD

**Issue by HTY-DBY** [fengx1a0/Bilibili_show_ticket_auto_order#50]
本人已魔改过了，效果很不错，这样不用盯着看是否成功了

**Comment by fengx1a0** [comment]
> 本人已魔改过了，效果很不错，这样不用盯着看是否成功了

支持二开，声音我就不加了因为不是所有人都喜欢，后面可能考虑加一个配置是否打开声音提示

**Comment by homulakk** [comment]
其实已经接入pushplus了，这种推送方式更灵活
