### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by Lh1aS** [fengx1a0/Bilibili_show_ticket_auto_order#51]
感谢大佬，我们这边陆陆续续抢了十几个人共20多张普票和3张vip票，止住了不少人去购买黄牛的意图，剩下了不少钱财。非常感谢，大家想尽一份心意赞助一下。可能不是很多，但也希望作者能给个赞助渠道，将来大大小小睿站的活动说不准还得依靠大佬，多谢。

**Comment by 123485k** [comment]
可以帮忙挂下吗，联系我邮箱，我自己挂都是假票

**Comment by fengx1a0** [comment]
> 感谢大佬，我们这边陆陆续续抢了十几个人共20多张普票和3张vip票，止住了不少人去购买黄牛的意图，剩下了不少钱财。非常感谢，大家想尽一份心意赞助一下。可能不是很多，但也希望作者能给个赞助渠道，将来大大小小睿站的活动说不准还得依靠大佬，多谢。

移步看：https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/issues/55
