### ISSUE TITLE
api.py中checkOrder()函数对于url返回结果data的正确性判断上存在问题

### ISSUE THREAD

**Issue by douyuqi** [fengx1a0/Bilibili_show_ticket_auto_order#52]
在我测试的真实情况中，checkorder()返回的data的key中确实包含errno，但是data['errno']=0，data['data']['list'][0]['status'] == 1也是成立的。
按照if "errno" in list(data.keys()):的判断逻辑，会一直为True反复提示“检测到网络波动，正在重新检查..."”。
考虑是否因为B站的接口返回格式发生了变化？
建议修改，按照errno的返回值进行判断。

**Comment by fengx1a0** [comment]
> 在我测试的真实情况中，checkorder()返回的data的key中确实包含errno，但是data['errno']=0，data['data']['list'][0]['status'] == 1也是成立的。 按照if "errno" in list(data.keys()):的判断逻辑，会一直为True反复提示“检测到网络波动，正在重新检查..."”。 考虑是否因为B站的接口返回格式发生了变化？ 建议修改，按照errno的返回值进行判断。

1.6.3中已修复
