### ISSUE TITLE
尽力卡点了,到底是没抢过那帮官方黄牛的脚本。

### ISSUE THREAD

**Issue by sans233333** [fengx1a0/Bilibili_show_ticket_auto_order#57]
如题

**Comment by 123485k** [comment]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/45510011/4323a39c-5b66-497e-880b-c317780756ec)
不要放弃

**Comment by sans233333** [comment]
22号的完全抢不过...

**Comment by fengx1a0** [comment]
加油

**Comment by SoranoRinji** [comment]
加油 多蹲一会可能就有捡漏的
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/21072983/205bd669-7f87-406d-ad8a-6f6fa75f42c3)
