### ISSUE TITLE
从GitHub下载并运行这个抢票程序时被Windows Defender报毒Bearfoos.A!ml

### ISSUE THREAD

**Issue by MilkTea0329** [fengx1a0/Bilibili_show_ticket_auto_order#58]
![IMG_1150](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/41126003/748da0ca-4370-40bb-922b-34e2f7b3a232)
开发者大大您好！请问开发者大大为什么我从GitHub下载并运行的这个抢票程序会被Windows Defender报毒Bearfoos.A!ml呢？

**Comment by fengx1a0** [comment]
> ![IMG_1150](https://user-images.githubusercontent.com/41126003/253587656-748da0ca-4370-40bb-922b-34e2f7b3a232.jpeg) 开发者大大您好！请问开发者大大为什么我从GitHub下载并运行的这个抢票程序会被Windows Defender报毒Bearfoos.A!ml呢？

怀疑我文件有问题可以自行运行开发板，运行方式和依赖在readme中都有

**Comment by MilkTea0329** [comment]
> > ![IMG_1150](https://user-images.githubusercontent.com/41126003/253587656-748da0ca-4370-40bb-922b-34e2f7b3a232.jpeg) 开发者大大您好！请问开发者大大为什么我从GitHub下载并运行的这个抢票程序会被Windows Defender报毒Bearfoos.A!ml呢？
> 
> 怀疑我文件有问题可以自行运行开发板，运行方式和依赖在readme中都有

不怀疑不怀疑，我已经确定这是误报毒了，请您别生气，谢谢您开发这个程序！

**Comment by fengx1a0** [comment]
那我close了哦

**Comment by MilkTea0329** [comment]
> 那我close了哦

好的，谢谢作者！
