### ISSUE TITLE
这怎么办

### ISSUE THREAD

**Issue by jeff78126** [fengx1a0/Bilibili_show_ticket_auto_order#59]
![U D{%5U$CJ2M F0L16C U9M](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/91967507/ffa303ce-5c5a-4c97-a0d7-e1d3c20b6665)

**Comment by fengx1a0** [comment]
> ![U D{%5U$CJ2M F0L16C U9M](https://user-images.githubusercontent.com/91967507/253585404-ffa303ce-5c5a-4c97-a0d7-e1d3c20b6665.png)

没出现过这问题，可能是你的系统问题，或者多试几次

**Comment by jeff78126** [comment]
重启了电脑可以跑了，但是会闪退

**Comment by jeff78126** [comment]
选好购买人后就闪退

**Comment by fengx1a0** [comment]
> 选好购买人后就闪退

是最新版的吗

**Comment by fengx1a0** [comment]
截一下报错图吧，cmd运行程序
