### ISSUE TITLE
大佬！bw预约能写吗？

### ISSUE THREAD

**Issue by Cccynics** [fengx1a0/Bilibili_show_ticket_auto_order#60]
抢不过根本抢不过，线下的名额就是一个僧多肉少，想问一下只能纯靠手抢吗？还是说也是可以写出来的。

**Comment by fengx1a0** [comment]
> 抢不过根本抢不过，线下的名额就是一个僧多肉少，想问一下只能纯靠手抢吗？还是说也是可以写出来的。

给开发费今晚给你赶出来，我收的也不多，1小时200我预计4小时就能做出来，抢票项目我写写改改了3天

**Comment by fengx1a0** [comment]
独家特版哦~只给你~可以签合同

**Comment by Cccynics** [comment]
不至于，相比之下身体健康比较重要，熬夜写代码太痛苦了！！授人以鱼不如授人以渔嘿嘿，如果写的话也是python吗？要用到什么方法？求指点，我可以交学费！

**Comment by fengx1a0** [comment]
> 不至于，相比之下身体健康比较重要，熬夜写代码太痛苦了！！授人以鱼不如授人以渔嘿嘿，如果写的话也是python吗？要用到什么方法？求指点，我可以交学费！

b站看看黑马就行

**Comment by Cccynics** [comment]
> 
好的 有空去学习
