### ISSUE TITLE
验证码每隔一段时间就要重新验证这个能解决吗QAQ

### ISSUE THREAD

**Issue by Polaris456** [fengx1a0/Bilibili_show_ticket_auto_order#63]

**Comment by Polaris456** [comment]
我给你赞助了1块钱。不多，不知道能不能看见

**Comment by fengx1a0** [comment]
> 我给你赞助了1块钱。不多，不知道能不能看见

感谢，这是b站的验证，因为没有你在购买界面显示的是已售罄，所以你一直请求购买是肯定会被弹验证或者封ip的，这不是你我能决定的事情
