### ISSUE TITLE
对于仅限APP购买的演出可以吗

### ISSUE THREAD

**Issue by QinMoMeak** [fengx1a0/Bilibili_show_ticket_auto_order#65]
在网页端可以打开商品详情网站，显示仅支持APP购买，可我看APP上也是个网站。。这种的可以使用本项目购买吗

**Comment by fengx1a0** [comment]
> 在网页端可以打开商品详情网站，显示仅支持APP购买，可我看APP上也是个网站。。这种的可以使用本项目购买吗

bml试过的都知道，老粉懂得都懂
