### ISSUE TITLE
缺少配送信息

### ISSUE THREAD

**Issue by youah123** [fengx1a0/Bilibili_show_ticket_auto_order#66]
![Screenshot_2023-07-16-13-52-29-420_com.tencent.mm.png](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/94919755/087ab80b-403f-42de-9ce1-bc80b5aee927)

遇到这个问题了，请问一下各位大佬，怎么解决呀？

**Comment by fengx1a0** [comment]
你买的什么票
