### ISSUE TITLE
请问购票人序号只能选零（选其他会报错），但选择0后会提示“购票数量不正确”，怎么办啊

### ISSUE THREAD

**Issue by Nameles12** [fengx1a0/Bilibili_show_ticket_auto_order#67]

**Comment by homulakk** [comment]
买的哪一场的

**Comment by Nameles12** [comment]
> 买的哪一场的
如果票数为零是不是就会跳出这个啊

**Comment by Nameles12** [comment]
> 买的哪一场的
21号的，如果票数为零是不是就会跳出这个啊

**Comment by Nameles12** [comment]
> 买的哪一场的

21的，如果票数为零是不是就会跳出这个啊

**Comment by Lum1n0us1** [comment]
你是用的最新版的吗

**Comment by Nameles12** [comment]
> 你是用的最新版的吗

是有“滑块验证”的版本。

**Comment by Lum1n0us1** [comment]
除了最初版后面的版本都有坏块验证，你是不是用错盗版了，几千个人用了一周多没反应过你这种问题

**Comment by Nameles12** [comment]
> 

那我再下一次试试，正常情况应该显示什么啊

**Comment by Nameles12** [comment]
> 除了最初版后面的版本都有滑块验证，你是不是用错盗版了，几千个人用了一周多没反应过你这种问题

那我再下一次试试，正常情况应该显示什么啊

**Comment by fengx1a0** [comment]
> > 除了最初版后面的版本都有滑块验证，你是不是用错盗版了，几千个人用了一周多没反应过你这种问题
> 
> 那我再下一次试试，正常情况应该显示什么啊

正常显示开始抢票，再选完购票信息后

**Comment by SoranoRinji** [comment]
检查一下你在脚本里登录的B站账号里有没有购票人信息

**Comment by Nameles12** [comment]
> 检查一下你在脚本里登录的B站账号里有没有购票人信息

对的，就是这个问题，已经抢到了，非常感谢
