### ISSUE TITLE
请问运行python login.py后就会闪退该怎么解决啊？

### ISSUE THREAD

**Issue by wy5181** [fengx1a0/Bilibili_show_ticket_auto_order#68]
![G%L3{9%8WS{C%9S3DPU35ZR](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139739978/bcae7c9e-f367-430f-a6b8-54d05af38b28)
之后他会出现一个这样的界面，然后秒退
![Screenshot_2023-07-17-16-58-48-743_com miui galle](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139739978/1f6abaa0-6e8b-4588-818a-bdf852526356)

**Comment by fengx1a0** [comment]
报错不截全，不知道你是什么问题

**Comment by wy5181** [comment]
> 报错不截全，不知道你是什么问题

大佬，已经解决这个问题了，是驱动安装错了。现在就是运行第二个的时候会显示这样的，说模块没有，咋解决啊
![M 9Y`UPEE6__6V5S_PC0 VM](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139739978/c43c2c1a-7a9f-43af-9dd7-fe9ea442921c)

**Comment by wy5181** [comment]
> > > 报错不截全，不知道你是什么问题
> > 
> > 
> > 大佬，已经解决这个问题了，是驱动安装错了。现在就是运行第二个的时候会显示这样的，说模块没有，咋解决啊 ![M 9Y`UPEE6__6V5S_PC0 VM](https://user-images.githubusercontent.com/139739978/254144147-c43c2c1a-7a9f-43af-9dd7-fe9ea442921c.png)
> 
> 你源码运行了，应该知道怎么装相关包吧，而且我都给了requirements.txt了

> 不知道怎么装，一点看不懂【害怕】

**Comment by fengx1a0** [comment]
那就运行exe啊

**Comment by wy5181** [comment]
> 那就运行exe啊

啊？我真的基本上是一点不懂

**Comment by fengx1a0** [comment]
exe只要按照主页说明双击运行，双击运行程序不会吗，就跟你打游戏一样点开

**Comment by wy5181** [comment]
> exe只要按照主页说明双击运行，双击运行程序不会吗，就跟你打游戏一样点开

运行python login.py
python main.py
python geetest.py
这些吗？还是运行哪个，我“登录”和“验证“都能正常运行，就抢票不行，没有plyer模块

**Comment by fengx1a0** [comment]
？？？？

**Comment by wy5181** [comment]
> ？？？？

咋了，大佬

**Comment by homulakk** [comment]
> > ？？？？
> 
> 咋了，大佬

别急,他急了,你听我说,你有看到release里面的压缩包吗,里面有三个后缀exe结尾的程序,分别是登录.exe 滑块验证.exe 和抢票.exe
首先呢你使用鼠标 双击这个登陆.exe 然后呢会弹出浏览器让你登陆你登陆就行 登录完之后呢 你再双击抢票.exe,按照弹出的窗口里的指示步骤一步一步来就行了  
具体来说
    第一步:你要先填入你要抢的漫展的网页端链接 
    例如bml的:https://show.bilibili.com/platform/detail.html?id=73752&from=pc_search 回车
    第二步:选择场次序号 回车
    第三步:选择票种序号 回车
    第四步:填写购票人信息或者选择实名信息 回车
完成上面步骤 你已经可以快乐抢票了,至于滑块验证.exe 你也可以再这之后运行 也是会有一个浏览器弹出 但是不要着急 当需要验证时 会有弹窗提示"需要滑块验证" 你点击之后 这个浏览器会自动跳转到滑块验证的页面 你只需动动小手即可

**Comment by wy5181** [comment]
> > > ？？？？
> > 
> > 
> > 咋了，大佬
> 
> 别急，他急了，你听我说，你有看到release里面的压缩包吗，里面有三个后缀exe结尾的程序，分别是登录.exe 滑块验证.exe 和抢票.exe 首先呢你使用鼠标 双击这个登陆.exe 然后呢会弹出浏览器让你登陆你登陆就行 登录完之后呢 你再双击抢票.exe，按照弹出的窗口里的指示步骤一步来就行了 具体来说 第一步：你要先填入你要抢的漫展的网页端链接 例如 bml的：https://show.bilibili.com/platform/detail.html?id=73752&from=pc_search 回车 第二步：选择场次序号 回车 第三步：选择票种序号 回车 第四步：填写购票人信息或者选择实名信息 回车完成上面步骤 你已经可以快乐抢票了,至于滑块验证.exe 你也可以再这之后运行 也是会有一个浏览器弹出 但是不要着急 当需要验证时 会有弹窗提示"需要滑块验证" 你点击之后 这个浏览器会自动跳转到滑块验证的页面 你只需动动小手即可


> > > ？？？？
> > 
> > 
> > 咋了，大佬
> 
> 别急,他急了,你听我说,你有看到release里面的压缩包吗,里面有三个后缀exe结尾的程序,分别是登录.exe 滑块验证.exe 和抢票.exe 首先呢你使用鼠标 双击这个登陆.exe 然后呢会弹出浏览器让你登陆你登陆就行 登录完之后呢 你再双击抢票.exe,按照弹出的窗口里的指示步骤一步一步来就行了 具体来说 第一步:你要先填入你要抢的漫展的网页端链接 例如bml的:https://show.bilibili.com/platform/detail.html?id=73752&from=pc_search 回车 第二步:选择场次序号 回车 第三步:选择票种序号 回车 第四步:填写购票人信息或者选择实名信息 回车 完成上面步骤 你已经可以快乐抢票了,至于滑块验证.exe 你也可以再这之后运行 也是会有一个浏览器弹出 但是不要着急 当需要验证时 会有弹窗提示"需要滑块验证" 你点击之后 这个浏览器会自动跳转到滑块验证的页面 你只需动动小手即可

![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/139739978/912f3177-12c2-4fd6-8757-02764988b411)
哪来的压缩包

**Comment by homulakk** [comment]
https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/releases
这个链接

**Comment by wy5181** [comment]
> https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/releases 这个链接

感谢大佬😭，终于能用了

**Comment by wy5181** [comment]
> ？？？？

抱歉抱歉😭，麻烦你了，感谢

**Comment by hell169** [comment]
> > > ？？？？
> > 
> > 
> > 咋了，大佬
> 
> 别急，他急了，你听我说，你有看到release里面的压缩包吗，里面有三个后缀exe结尾的程序，分别是登录.exe 滑块验证.exe 和抢票.exe 首先呢你使用鼠标 双击这个登陆.exe 然后呢会弹出浏览器让你登陆你登陆就行 登录完之后呢 你再双击抢票.exe，按照弹出的窗口里的指示步骤一步来就行了 具体来说 第一步：你要先填入你要抢的漫展的网页端链接 例如 bml的：https://show.bilibili.com/platform/detail.html?id=73752&from=pc_search 回车 第二步：选择场次序号 回车 第三步：选择票种序号 回车 第四步：填写购票人信息或者选择实名信息 回车完成上面步骤 你已经可以快乐抢票了,至于滑块验证.exe 你也可以再这之后运行 也是会有一个浏览器弹出 但是不要着急 当需要验证时 会有弹窗提示"需要滑块验证" 你点击之后 这个浏览器会自动跳转到滑块验证的页面 你只需动动小手即可

/
/

**Comment by hell169** [comment]
> > > ？？？？
> > 
> > 
> > 咋了，大佬
> 
> 别急，他急了，你听我说，你有看到release里面的压缩包吗，里面有三个后缀exe结尾的程序，分别是登录.exe 滑块验证.exe 和抢票.exe 首先呢你使用鼠标 双击这个登陆.exe 然后呢会弹出浏览器让你登陆你登陆就行 登录完之后呢 你再双击抢票.exe，按照弹出的窗口里的指示步骤一步来就行了 具体来说 第一步：你要先填入你要抢的漫展的网页端链接 例如 bml的：https://show.bilibili.com/platform/detail.html?id=73752&from=pc_search 回车 第二步：选择场次序号 回车 第三步：选择票种序号 回车 第四步：填写购票人信息或者选择实名信息 回车完成上面步骤 你已经可以快乐抢票了,至于滑块验证.exe 你也可以再这之后运行 也是会有一个浏览器弹出 但是不要着急 当需要验证时 会有弹窗提示"需要滑块验证" 你点击之后 这个浏览器会自动跳转到滑块验证的页面 你只需动动小
但是现在用网址上的连接运行登录.exe后，不会跳出登录b站的网页，然后打开的exe会显示几行东西，然后闪退
