### ISSUE TITLE
我在测试的时候有的链接一直无响应

### ISSUE THREAD

**Issue by axiliya2568** [fengx1a0/Bilibili_show_ticket_auto_order#7]
https://show.bilibili.com/platform/detail.html?id=71931比如这个就按回车就无响应，ccg的就能跳转订单

**Comment by axiliya2568** [comment]
还有想请问下商品的sectoken是怎么获得的啊，能不能再开售前获得啊谢谢

**Comment by axiliya2568** [comment]
也就是每个商品对应码除了时间戳后面project前面的是如何得到，望大佬解答

**Comment by axiliya2568** [comment]
> 还有想请问下商品的sectoken是怎么获得的啊，能不能再开售前获得啊谢谢
能不能加一个打印出token，我在api.py里改了，但未在exe里输出

**Comment by axiliya2568** [comment]
如果选择的是未开售的商品，在选择完购票人后会提示失败信息:您的账号存在异常，展示无法购票，然后就闪退了

**Comment by axiliya2568** [comment]
希望能增加一个获取购买token完显示token的功能，感谢大佬

**Comment by fengx1a0** [comment]
> [https://show.bilibili.com/platform/detail.html?id=71931比如这个就按回车就无响应，ccg的就能跳转订单](https://show.bilibili.com/platform/detail.html?id=71931%E6%AF%94%E5%A6%82%E8%BF%99%E4%B8%AA%E5%B0%B1%E6%8C%89%E5%9B%9E%E8%BD%A6%E5%B0%B1%E6%97%A0%E5%93%8D%E5%BA%94%EF%BC%8Cccg%E7%9A%84%E5%B0%B1%E8%83%BD%E8%B7%B3%E8%BD%AC%E8%AE%A2%E5%8D%95)

已修复

**Comment by fengx1a0** [comment]
> 还有想请问下商品的sectoken是怎么获得的啊，能不能再开售前获得啊谢谢

技术细节不解释，自己看代码

**Comment by fengx1a0** [comment]
> 不能加一个打印出token，我在api.py里改了，但未在exe里输出

只完成正常功能，如需要添加辅助功能请二开表明参考出处

**Comment by fengx1a0** [comment]
> 如果选择的是未开售的商品，在选择完购票人后会提示失败信息:您的账号存在异常，展示无法购票，然后就闪退了

已修复

**Comment by singledog65** [comment]
我在测试的时候遇到了显示抢到了票但是订单那边没有任何东西，也没有滑条验证的情况，请问怎么解决，抢bw票用的

**Comment by fengx1a0** [comment]
> 我在测试的时候遇到了显示抢到了票但是订单那边没有任何东西，也没有滑条验证的情况，请问怎么解决，抢bw票用的

前面close的issue已有说明，还有什么bug请反馈，没有请close此issue
