### ISSUE TITLE
显示账号存在异常

### ISSUE THREAD

**Issue by QinMoMeak** [fengx1a0/Bilibili_show_ticket_auto_order#70]
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/57384745/5559726d-4fd5-449f-8c17-180281fe461b)
别的演出没问题 请问是因为预售的原因还是移动端的限制？

**Comment by axiliya2568** [comment]
脚本暂时不能用，等更新吧

**Comment by axiliya2568** [comment]
被叔叔修复了这场

**Comment by SoranoRinji** [comment]
部分演出是等待开票的情况下使用脚本时命令行会出现这个输出，这个情况下如果刷的过多可能会封ip

**Comment by axiliya2568** [comment]
> > 被叔叔修复了这场
> 
> 坏了 我还跟同学说能抢到…… 那是不是都不能用 手抢的概率也大些

对的，可以多叫几个同学，用人海战术
