### ISSUE TITLE
大大，有人在视频网站引流该脚本

### ISSUE THREAD

**Issue by Lh1aS** [fengx1a0/Bilibili_show_ticket_auto_order#71]
如题，有人在Bilibili发布视频宣扬该脚本进行引流，是否需要抵制该一行为？

**Comment by fengx1a0** [comment]
> 如题，有人在Bilibili发布视频宣扬该脚本进行引流，是否需要抵制该一行为？

附上bv号啊

**Comment by fengx1a0** [comment]
> > > 如题，有人在Bilibili发布视频宣扬该脚本进行引流，是否需要抵制该一行为？
> > 
> > 
> > 附上bv号啊
> 
> BV1j14y197M3

我也无能为力，点了个举报，这种事情全靠素质

**Comment by awasl** [comment]
这些人怎么什么都往b站发，还贴个原神标签，真ex

**Comment by fengx1a0** [comment]
> 这些人怎么什么都往b站发，还贴个原神标签，真ex

家里没有亲人

**Comment by Lh1aS** [comment]
> > > > 如题，有人在Bilibili发布视频宣扬该脚本进行引流，是否需要抵制该一行为？
> > > 
> > > 
> > > 附上bv号啊
> > 
> > 
> > BV1j14y197M3
> 
> 我也无能为力，点了个举报，这种事情全靠素质

经过不懈努力那个作者终于删除了

**Comment by fengx1a0** [comment]
欧克，谢谢
