### ISSUE TITLE
不在PC网页端上售卖的门票能够购买吗？

### ISSUE THREAD

**Issue by Umi7899** [fengx1a0/Bilibili_show_ticket_auto_order#75]
### 问题描述
上海Fes的门票似乎在[PC端网址](https://show.bilibili.com/platform/detail.html?msource=mall_piaowu_pc_15581_banner&id=75162)上不可售：
![EV86GF)OO%Z{{TO0SFV4%5](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/79504156/abcab489-41b4-4fb5-beca-38b11d247cff)

我自己尝试了一下使用手机App打开购票页面并分享[手机端链接](https://mall.bilibili.com/mall-dayu/neul/shareticket?page=ticket_detail&id=75162)，虽然能在PC上打开手机版的页面，脚本也能够读取url，但在尝试购票时似乎还是会报错。

### 错误截图
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/79504156/855fce0c-91f0-4952-8fd0-08ae34a53321)

我尝试了一下其他可以在PC端直接购买的未开售门票，返回的信息是“不可售”之类的信息，不是图里的“账号异常”。

所以这种门票是只能自己在手机上手动购买吗？希望能得到您的回复

**Comment by homulakk** [comment]
并不是，参考bml，脚本通用，账号异常的报错是因为还没开售，无论bw bml在未开售售期间都会报账号异常的错
然后就是提issue之前请确保之前没有出现过，不要重复提issue

**Comment by Umi7899** [comment]
> 并不是，参考bml，脚本通用，账号异常的报错是因为还没开售，无论bw bml在未开售售期间都会报账号异常的错 然后就是提issue之前请确保之前没有出现过，不要重复提issue

抱歉，没有注意到已经关闭的issue，谢谢您的回复
