### ISSUE TITLE
猫眼

### ISSUE THREAD

**Issue by Weishi-corroding** [fengx1a0/Bilibili_show_ticket_auto_order#76]
大佬可以帮忙写一个这个脚本的猫眼版吗
想要抢原神fes的票，抢票网址为
https://show.maoyan.com/qqw#/detail/265844?_blank=true
现在也是处在等退票的阶段
有偿都可以的真的很想要一张票
大佬看到可以联系我
e-mail：weishi_corroding@163.com
qq：1750191981
拜托了谢谢大佬T T

**Comment by fengx1a0** [comment]
b站票务我没脱产写了3天，目前看有些许困难，你也知道咸鱼黄牛那的票价，我是开源项目，所以目前只做b站票务了，不好意思哈

**Comment by Weishi-corroding** [comment]
可是猫眼和b站的应该不会差太多吧能在这个项目的基础上改吗T T

**Comment by Weishi-corroding** [comment]
真的有偿都行的

**Comment by Weishi-corroding** [comment]
黄牛那边的价格实在太高了原价五百他卖三千

**Comment by fengx1a0** [comment]
是啊，黄牛也用的科技，那我写出来科技给你是不是你也可以去卖3000的票了，工具的价值远大于帮你抢一张票，要是帮你抢一张票那还可以，直接给你生产力的工具那我的付出和回报就不成正比了欸，毕竟我也没有那么多时间，要不你可以看看github上的猫眼脚本，我记得有不少项目的

**Comment by Weishi-corroding** [comment]
？那你帮我抢一张票（bushi）好吧谢谢大佬了，github我不是没找过，可是大多数都是大麦网的，几乎看不到猫眼的项目，我试着自己写下吧不麻烦您了TT
