### ISSUE TITLE
提示相关

### ISSUE THREAD

**Issue by luocixi** [fengx1a0/Bilibili_show_ticket_auto_order#79]
提示
![image](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/59860644/1da982e3-2b78-4d7b-bd45-22bf7323c8ce)
但实际其他场的票可以买，图为：成都·COMIDAY26原创同人交流会（未开售）

**Comment by homulakk** [comment]
#75

**Comment by fengx1a0** [comment]
> 提示 ![image](https://user-images.githubusercontent.com/59860644/259339163-1da982e3-2b78-4d7b-bd45-22bf7323c8ce.png) 但实际其他场的票可以买，图为：成都·COMIDAY26原创同人交流会（未开售）



> 提示 ![image](https://user-images.githubusercontent.com/59860644/259339163-1da982e3-2b78-4d7b-bd45-22bf7323c8ce.png) 但实际其他场的票可以买，图为：成都·COMIDAY26原创同人交流会（未开售）

看主页，测试可用
