### ISSUE TITLE
大佬，小白有些问题想问问

### ISSUE THREAD

**Issue by PulyZ** [fengx1a0/Bilibili_show_ticket_auto_order#82]
这个脚本是在什么时候开始运行最好的啊，我看运行就一直在抢了，有些票好像是定点开抢的，但是我想把他丢在服务器上让他自己抢，我应该咋做

**Comment by PulyZ** [comment]
就是放在那里，然后让他到时间就自己抢

**Comment by ZianTT** [comment]
建议不要这么做，因为概率触发验证码的

**Comment by lanbears** [comment]
> 建议不要这么做，因为概率触发验证码的

会触发什么验证码呀

**Comment by PulyZ** [comment]
哦哦，那应该在什么时候开始跑脚本最好啊

**Comment by SoranoRinji** [comment]
建议整点开始的时候跑，不然ip有概率被风控（如果是开始前几分钟开始跑的话）
