### ISSUE TITLE
“该应用无法在电脑上运行”求助

### ISSUE THREAD

**Issue by lrastar** [fengx1a0/Bilibili_show_ticket_auto_order#88]
@issue
<img width="858" alt="image" src="https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/143856673/73066f76-6082-443b-9e0b-226f13e3ae6c">
<img width="1271" alt="image" src="https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/143856673/14ad9b11-1865-4147-9a1a-3d49c4e0c4de">
第一次见不知道如何解决

**Comment by Andy-Chuck** [comment]
直接运行那个 exe 就行了，或者用 python 运行 .py 文件
你这是拿 python 运行 exe 了？

**Comment by doxsw** [comment]
虽然我也不知道是什么问题,但是我把系统重装了一遍就好了

**Comment by lrastar** [comment]
> 直接运行那个 exe 就行了，或者用 python 运行 .py 文件 你这是拿 python 运行 exe 了？

虽然我也不知道是什么问题,但是我把系统重装了一遍就好了

**Comment by lrastar** [comment]
非常谢谢大佬们创造了这个工具和维护
