### ISSUE TITLE
无法调用Edge浏览器

### ISSUE THREAD

**Issue by lrastar** [fengx1a0/Bilibili_show_ticket_auto_order#98]

**Comment by Just-Prog** [comment]
命令提示符里面运行显示什么报错

**Comment by lrastar** [comment]
系统找不到MicrosoftWebDriver.exe
<img width="1212" alt="image" src="https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/143856673/a57456c4-a2b0-40f6-8ba1-0f5b92e402a1">

**Comment by lrastar** [comment]
应该是安装依赖[Edgewebdriver]，但是我下载Edgewebdriver之后我不知道怎么用😂
