### ISSUE TITLE
新验证码

### ISSUE THREAD

**Issue by QianQiuZy** [fengx1a0/Bilibili_show_ticket_auto_order#99]
CPSP抢票时弹出了新的验证码，是B站登录的选字验证码而不是拉块儿验证码，运行默认的拉块儿无法解决（忘截图了后面看看还能不能截到）

**Comment by QianQiuZy** [comment]
抢票的时候我手动在会员购拉出的选字验证码之后可以正确抢票（抱歉当时比较急没截图）目前CPSP链接还在，应该都是用的新选字验证码，拉远滑块验证码无效
![微信图片_20240402114019](https://github.com/fengx1a0/Bilibili_show_ticket_auto_order/assets/103925928/e3b374ea-ecf0-4742-97c7-09b10a3e8450)

**Comment by Zackyooo** [comment]
现在验证码已经不是滑块了吗。那该怎么手动验证，自己登录会员购抢的时候验证吗

**Comment by QianQiuZy** [comment]
> 现在验证码已经不是滑块了吗。那该怎么手动验证，自己登录会员购抢的时候验证吗
我目前已知的只有CPSP出现了一次点字验证，其余时间正常，概率出现，第一波放的时候没有第二波出现了

**Comment by QianQiuZy** [comment]
> 现在验证码已经不是滑块了吗。那该怎么手动验证，自己登录会员购抢的时候验证吗

我目前已知的就CPSP出现了一次点字验证，第一波抢票的时候没出现第二波出现了，其余链接抢票的时候正常

**Comment by Zackyooo** [comment]
> > 现在验证码已经不是滑块了吗。那该怎么手动验证，自己登录会员购抢的时候验证吗
> 
> 我目前已知的就CPSP出现了一次点字验证，第一波抢票的时候没出现第二波出现了，其余链接抢票的时候正常

出现点字验证是咋解决的

**Comment by QianQiuZy** [comment]
> > > 现在验证码已经不是滑块了吗。那该怎么手动验证，自己登录会员购抢的时候验证吗
> > 
> > 
> > 我目前已知的就CPSP出现了一次点字验证，第一波抢票的时候没出现第二波出现了，其余链接抢票的时候正常
> 
> 出现点字验证是咋解决的

刷新网页出现立即购票点一下，点完验证码之后就可以正常使用脚本了，基本上是手动解决的

**Comment by Hobr** [comment]
用这个https://github.com/Just-Prog/Bilibili_show_ticket_auto_order
